/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

    getting_started: [
        'getting_started/getting-started',
        'getting_started/software-identification',
        'getting_started/software-security',
        'getting_started/license-compliance',
        'getting_started/cravex',
    ],

    about: [
        'about/contribute',
        'about/events',
        'about/meetings',
        'about/news',
        'about/releases',
        'about/standards',
        'about/credits',
    ],

};

export default sidebars;
